offa/android-foss

README.md
Open source Instagram client.
Obviously Instagram implies NonFreeNet, but seeing you have Twitter/Reddit clients, I assume it meets the criteria.
Note that we were previously called InstaGrabber, and F-Droid still retains that name; We plan to rebrand on next stable release (it has already been done in alpha releases).
related: https://gitlab.com/fdroid/fdroiddata/-/merge_requests/7390
=> Add Barinsta

README.md
FlorisBoard is yet another open-source keyboard but packed with many features and it's lightweight.
=> FlorisBoard added

README.md
DecSync CC added
Clock+ removed: 
unmaintained since 2017, there might be forks, alarms not working on Android 10 (at least for me)
How should we proceed with it? Just remove or add a info?
=> Add DecSync CC, Remove Clock+

README.md
- Remove deprecated TrebleShot app
- Add SnapShot for new FileSharing option
- Add Joplin app on Notes section, even though it can count as ToDos as well
=> Improve FileSharing and Notes headers

README.md
Apps: Limbo, GMaps WV, Mastodon, WordPress, Noten Learner, Phonograph Plus, Music, Thud, Weather
Games: Lemuroid (removed from Retro category & added to Emulator), Dolphin, J2ME Loader, RetroArch
---
https://github.com/offa/android-foss/pull/200#discussion_r806027773
Please reconsider adding [lichess](https://github.com/lichess-org/lichobile), this is the only chess site with all features. for [free](https://lichess.org/features).
Lichess is a great revolution for chess community & it inspired many other opensource chess sites.
https://lichess.org/blog/X-2TABUAANCqhnH5/lichess-end-of-year-update-2020
> with peaks of over 110,000 players online
You can see live players here
Thanks!
=> Emulator Category + some new* apps

README.md
PCAPdroid is a privacy-friendly app which lets you track, analyze and block the connections made by the other apps in your device. It also allows you to export a PCAP dump of the traffic, inspect HTTP requests/replies, decrypt TLS traffic and much more
=> Add PCAPdroid

README.md
CTemplar no longer exists since May 26 of 2022.
https://ctemplar.com/ctemplar-is-shutting-down/
=> CTemplar no longer exists

README.md
Orgzly is an Editor/Viewer for org files (see https://orgmode.org/).
I use it both for notes and todos, so I would propose we add it in both sections.
And I think we should also include the amazing fork of syncthing-android.
=> Add Syncthing-Fork & Orgzly

README.md
Since there are two the same records for Battery Tool, I think one of them should be removed.
=> Remove a duplicate of Battery Tool

README.md
~Yalp Store~ - inactive
~LTE Cleaner~ - https://github.com/TheRedSpy15/LTECleanerFOSS/discussions/321
~Bromite~ - inactive (check their issue tracker) | also https://github.com/uazo/bromite-buildtools/issues/182
Added new categories - URL Manipulation, Email Aliases
Added new apps - Accrescent, Jerboa, Simple Contacts Pro SE, AnonAddy Android, SimpleLogin, Thumb-Key, Cheogram, Moshidon, jtx Board, Léon, LinkSheet, Tarnhelm, Wall You, Zade's Wallpaper.
=> May 2023 update

README.md
The Github repo linked is now an archive and the project has moved to Codeberg.
=> Update Clima link from github to codeberg

README.md
- New: [Apps] FadCam, Aaru, FDTracker, Element X, Mercurygram, FocusPodcast, Tack, Canta, Geto, Network Survey, Nix-on-Droid, Json List, KeyStoreViewer, Gadgetbridge, Launch Chat, Materials Live Wallpaper, Paperize, Peristyle, Slideshow Wallpaper, Wave Lines Live Wallpaper, Rain (#403) | [Games] Minute Maze, Chip Defense, Flowit
- Other minor updates: Openlib, Feeder, LogFox, Breezy Weather, aShell You (moved from Games/Miscellaneous to Apps/System), freeDictionaryApp,
=> July24 updates

README.md
1. NekoX is not in active development now and the older releases are buggy or lack recent feature changes. We may consider adding a fork of it [https://github.com/dic1911/NekoX](https://github.com/dic1911/NekoX)
2. Removed Quacker as we have Squawker already.
=> Removed unmaintained NekoX and Quacker

README.md
The app has been archived and unmaintained for two years now, which is a huge security risk by its very nature. There are several other authenticator apps in this list, so `andOTP` should not be listed anymore.
=> Remove the unmaintained andOTP app

README.md
Bitwarden has retired their old C# mobile app in favor of new native Kotlin Android and iOS Swift ones. This includes changes to their repo URLs, and with respect to Android: `https://github.com/bitwarden/mobile` -> `https://github.com/bitwarden/android`.
=> Update Bitwarden repo URL with newer one

README.md
Remove SkyDroid for project inactivity, also the app seems to be broken, as it doesn't load the apps from the  indexes.
=> remove SkyDroid

README.md
Addy.io Android moved to GitHub.
https://gitlab.com/Stjin/anonaddy-android#note-please-read
=> Change addy.io link.

README.md
**Title:** Add Tuta Calendar to Utilities Section  
**Description:**  
This PR adds [Tuta Calendar](https://f-droid.org/en/packages/de.tutao.calendar/) to the **Utilities** section of the README. Tuta Calendar is a privacy-focused, open-source calendar app available on F-Droid.  
**Changes:**  
- Added Tuta Calendar under the Utilities section with a link to its F-Droid page.
=> Add Tuta Calendar

README.md
Mihon is a privacy-focused, open-source manga reader for Android, forked from Tachiyomi with continued development and extension support
=> Kahon app added

README.md
A kiosk browser that can turn your Android device into a locked-down web page in fullscreen mode.
---
Source code: https://github.com/nktnet1/webview-kiosk
Website: https://webviewkiosk.nktnet.uk
=> feat: add webview kiosk to the browser category
