offa/android-foss

README.md
Shelter is a very useful app which utilizes Android's work mode to isolate apps and "freeze" them
=> Add Shelter to System apps

README.md
Aegis:
-----
> Aegis Authenticator is a free, secure and open source app for Android to manage your 2-step verification tokens for your online services.
> https://getaegis.app/
Bromite:
-----
> Bromite is a Chromium fork with ad blocking and enhanced privacy; take back your browser
> https://www.bromite.org/
=> Add Aegis & Bromite

README.md
DNS66 and Personal DNS Filter.
=> Added 2 more adblockers

README.md
added 'OpenNoteScanner' Document scanning+PDF creater app
=> added Document scanner category and 2 more apps

README.md
Adding 3 FOSS video players.
I'm the author of one of the video players (the last one - with matching GitHub username).
=> Update video players

README.md
=> Add Fermata Media Player

README.md
Tsacdop is a FOSS podcast player developed by me, I hope it can be added to this list :)
=> Added Tsacdop in Music&Audio Player category 

README.md
Pulse Music app's development has been abandoned. The developer has archived the repository and the releases have been removed from GitHub too!
=> Pulse Music removed

README.md
Added Metro music player. It is a fork of Retro music player with Google Play API removed and all pro features unlocked.
=> Added Metro music player.

README.md
Added Stingle Photos, Koler Dialer and Privacy Browser app. Removed Essential Launcher as it got abandoned.
=> Added three apps and removed one

README.md
Added Loop Habit Tracker, Editor and Cryptocam.
=> Added 3 apps

README.md
Added the Auxio local music player by OxygenCobalt.
=> Added 1 app to Music & Audio Player

README.md
Made a new section for call related apps(This reverts [869be58](https://github.com/offa/android-foss/commit/869be58108631203bc89e3df4fadcabdeb76f728) ). Added Silence app which can be used to filter and block calls
=> Added new Call blocker section; Silence app added 

README.md, check_manually.sh
- Small improvement on shell command
- Create functionality to check github repos for deprecated repos, should be removed
- Remove deprecated repos
Image showing the deprecated repos:
=> Add functionality to check deprecated repos on github

README.md
- "Privacy Indicators" let you know when any other app used your camera and mic (soon GPS as well)
- "Exodus" will check all installed apps on the device and report the number of trackers and permissions each app has.
=> Add two new apps for tracking and privacy

check_manually.sh
- Split the code into functions improving:
- Readability
- Possibility to add new checks 
- Removed Fdroid checks, as it was already being done in full `http` check
=> Refactor check_manually to improve readability

README.md
=> Added Tachiyomi

New apps addition
Flashcard apps [**New**]
- AnkiDroid
- Anki Image Occlusion
- AnkiEditor
- ForgetMeNot
Keyboard
- 8VIM 
Media Frontends
- Twire (for Twitch)
Miscellaneous
- Goodtime (Pomodoro Timer)
- Vigilante (Privacy Indicator alternative)
- dvd (download videos from multiple sources)
- SpotiFlyer (downloaded music/songs from multiple sources)
- SubHub (Subtitle downloader)
- KDE Connect
- (removed Feeder to RSS section)
Music
- Dialog Music Player (minimal music player)
- SongTube (currently available on [izzy-repo](https://apt.izzysoft.de/fdroid/index/apk/com.artxdev.songtube))
Notes
- Quillnote
- Logseq (available on [izzy](https://apt.izzysoft.de/fdroid/index/apk/com.logseq.app))
Office
- OpenDocument
RSS Readers [**New**]
- Feeder
- NewsBlur
Science & Education [**New**]
- freeCodeCamp (available …
=> New apps addition

README.md
Tachiyomi's F-Droid link :)
Edit: @offa  keep it open. I'll keep adding Games in this pr & let you know when done.
=> Games [NEW]

README.md
- Sky Droid
- Appteka
- IzzyOnDroid
- NetHunter Store
=> Update README.md with new App Stores

README.md
https://play.google.com/store/apps/dev?id=7626572346998944846
All these 3 apps' apk available on GitHub with different package ID
Edit: Reminder : Don't forget to add new "Emulator"  to Table of contents for both Apps & Games section. Added with #216 PR
Thanks
=> GrapheneOS apps

README.md
**Image Manipulation** [_NEW*_]
- ImagePipe (removed from Miscellaneous)
- PrivacyBlur
- Easy Watermark (removed from Utilities)
- Scrambled Exif (removed from Miscellaneous)
- Exif Thumbnail Adder
=> New apps: PixelDroid | PxerStudio | PrivacyBlur | Simon Tatham's Puzzles | Exif Thumbnail Adder

README.md
Odysee: already available on F-droid app.
Atomic - Periodic Table - https://github.com/JLindemann42/Atomic-Periodic-Table.Android/issues/19
Monochromatic - project abandoned but really useful app. One of its own kind app, I request you to keep it here.
Cams - no issue, available on F-Droid
---
Update ToC Image Manipulation (#222)
---
Topic of discussion: 
[Marcel Bokhorst](https://github.com/M66B) archived all his projects & closed related XDA threads, which includes popular apps e.g. [XPrivacy](https://github.com/M66B/XPrivacy), [FairEmail](https://github.com/M66B/FairEmail), [NetGuard](https://github.com/M66B/NetGuard).
https://forum.xda-developers.com/t/closed-app-5-0-fairemail-fully-featured-open-source-privacy-oriented-email-app.3824168/page-1087
Short version: …
=> Odysee | Atomic - Periodic Table | Monochromatic | Cams

README.md
* ~Amaze File Manager~
* ~ONLYOFFICE Documents~
* Add `Text Editors` section
- Acode
- Move `Editor` to this section
=> New apps: Acode

README.md
Simple Clock revived again (#198), Joplin removed again (#205), Retro - https://gitlab.com/fdroid/rfp/-/issues/2120 ready
=> Filester | LinkHub | Retro | OpenTracks | Open Golf | RustDesk | Openreads

README.md
Neo-Store - Droid-ify renamed to Neo-Store (repo link changed) F-Droid will update the name from upcoming releases
K-9 Mail - repo link changed (https://k9mail.app/2022/06/13/K-9-Mail-and-Thunderbird.html)
=> Home Assistant | ObscuraCam | Audio Spectrum Analyzer | Liedgutverzeichnis | Tux Paint | OpenKeychain | Molly

README.md
- Xtra - https://github.com/crackededed/Xtra/issues/19
- Volta
- Chess
- Key Mapper
- Hex Launcher
- Tusky
- Husky
- Url checker
- Mumla
- PilferShush Jammer
- Motion Eye - F-Droid source code linked to: https://jairajjangle.github.io/motionEye_app_HomeSurveillanceSystem/
GH link: https://github.com/JairajJangle/motionEye_app_HomeSurveillanceSystem
**Translation** _[New*]_
- DeeepL (_removed from Miscellaneous_)
- The Translator
- SimplyTranslate Mobile
- LibreTranslator
- Arna Translate - https://github.com/MahanRahmati/translate/issues/2 , https://gitlab.com/fdroid/rfp/-/issues/2113
=> Translation apps

README.md
Seal: https://github.com/JunkFood02/Seal/issues/41
=> Torrent Client | Seal

README.md
Verify decentralized cryptographic identities on the go
=> Add Keyoxide

README.md
- F-Droid Classic
- OpenCalc
- Fedilab
- Everyday Tasks
- Shattered Pixel Dungeon
- Forkyz
- Converter NOW
- unitto (https://github.com/sadellie/unitto/issues/1)
=> New apps & games

README.md
Add Noto - minimal Android notes application.
https://github.com/alialbaali/Noto
=> Add Noto for notes

README.md
Extirpater best fits under Utilities category as it's a 1time thing.
From their description: _Use before selling your device, after enabling encryption, or after deleting many apps/files. Warning! Excessive use WILL destroy your device!_
=> Lunar Launcher | Nitter for Android | Mysterium VPN | FFShare | Feudal Tactics | Barcode Scanner | FutharkBoard

README.md
I added [Dark theme](https://github.com/phstudio2/Darktheme) from [PH Studio](https://github.com/phstudio2)  to your list.
=> Add Dark theme

README.md
- ~OpenCamera Sensors~ - archived
- Little File Explorer
- Karma Firewall
- Mastodon - updated fdroid link
- Megalodon
- Jami
- Meshenger
- GuitarFretboardTrainer
- InnerTune
- ~Quillnote~ replaced with it's fork Quillpad (https://github.com/msoultanidis/quillnote/issues/177#issuecomment-1319644880)
- Aggregator
- ChemistryLab
- Inure App Manager (https://gitlab.com/fdroid/rfp/-/issues/2247)
- Permission Pilot (https://gitlab.com/fdroid/rfp/-/issues/2260)
- Captive Portal Controller (https://gitlab.com/fdroid/rfp/-/issues/2233)
- Sensorkaren
- Sudoku
=> December22 new app list

README.md
Partisan SMS is the most popular fork of QKSMS.
=> Added Partisan SMS

README.md
"Music" is renamed to InnerTune, which is in the list 3 lines below.
=> Remove duplicate InnerTune entry ("Music")

README.md
- _Connect You_ 
- ShareX
- Image Resizer
- Super Image
- AnimePipe
- Practice Suit
- Treble Info
- _SystemUI Tuner_ - https://github.com/zacharee/Tweaker/issues/47
- Emacs
- _DroidVim_ - https://github.com/shiftrot/droidvim/issues/50
- OCR
- Trail Sense
- omWeather
- Dooz
- _LibreSudoku_ - https://github.com/kaajjo/Libre-Sudoku/issues/7
Adjusted "Text-to-Speech" category alphabetically.
Changed "Acode" website to their GH repo.
~LeafPic Revived~ - Archived
~Calculator++~ - Archived
=> March 2023 update

README.md
https://gitlab.com/ondrejfoltyn/nunti
=> added Nunti

README.md
Contacts--
1. Connect You: added IzzyDroid store link
2. OpenContacts: added as new entry. Gitlab & F-Droid
Dialer--
1. OpenContacts: added as new entry. Gitlab & F-Droid
OpenContacts has inbuilt dialer function too.
=> New addition in contacts & dialer, and one modification in contacts.

README.md
Kvaesitso is a search focused, free and open source launcher for Android.
Wondered why nobody knew about it, its really fantastic app with extensible search functionality unlike no other apps.
It has modern Material You theme.
Git: https://github.com/MM2-0/Kvaesitso
=> Added Kvaesitso & Orgro

README.md
+ Record You
+ Trivia You
+ Translate You
They are all modern Material you apps, which are minimal and simple by Bnryo
=> Added app from Bnryo

README.md
=> Add Sleuth

README.md
- Lato
- Burger Party
- Ball2Box
- RUTMath
- EtchDroid
- Linux Command Library
- Notesnook
- KryptEY
=> July 2023 Update

CONTRIBUTING.md
Related to #302.
/cc @IzzySoft
=> Update contribution docs

README.md
cherry pickable, but all of them stick to the contribution-guidelines
=> Adds 3 Apps (Signal-Foss, Smart EggTimer, uLogger)

README.md
=> Replace 'Universal Android Debloater GUI' with 'Android Debloat List'

README.md
Open Sudoku moved to GitLab from GitHub.
=> Open Sudoku git move

README.md
Forkyz moved from GitHub to GitLab.
=> Forkyz git move

README.md
=> New app - Call Recorder in Misc category

README.md
#340
I'm adding:
- WifiAnalyzer to System category, there is already some kind of Network Analyzer - PCAPdroid.
- ConnectBot to Utilities category - as it is a utility to connect to remote system
- AVNC to Utilities too - utility to connect to remote system
=> Add AVNC, ConnectBot, WifiAnalyzer and move Unitto

README.md
This includes:
- M-Droid
- Foxy Droid
- NetHunter Store
- Document Viewer (it's also vulnerable)
=> Remove abandoned apps

README.md
Recreate #305
Closes #290, #291
=> December23 update

README.md
=> Added a missing bracket

README.md
1. Licensed as *Free and Open Source Software*? - Yes, [BSD License](https://github.com/stsaz/phiola/blob/beta/LICENSE).
1. Source code available - [Yes](https://github.com/stsaz/phiola/tree/beta).
1. Keeps Privacy – No Advertisement, no Spyware! - No analytics or ads.
1. No proprietary elements - Yes, no proprietary component was used.
1. Stable (at least stable to use). - Yes. Even though the repo is marked as beta as some missing features being added, the app works as you would expect as a standalone music player.
1. Actively developed, maintained or supported? Yes. [stsaz](https://github.com/stsaz) doing great work. Check out his repo and star the project to show your support.
1. Documentation available? [Yes](https://github.com/stsaz/phiola/blob/beta/README.md)
1. Free of charge? …
=> Add phiola audio player

README.md
See https://github.com/Helium314/HeliBoard/releases/tag/v1.0-alpha1
=> Rename OpenBoard Upgrade to HeliBoard

README.md
- Aniyomi is a Tachiyomi fork that enables streaming features for anime watching.
- Mihon is a Tachiyomi successor from the developer of another fork called [TachiyomiSY](https://www.reddit.com/r/animepiracy/comments/197vwou/first_version_of_mihon_a_tachiyomi_succesor_from/).
=> Add Aniyomi

README.md
=> Add Custom Uploader

README.md
Added reference to MedTimer, a FOSS medication reminder app
=> Add MedTimer

README.md
aShell You is a fork of an app named aShell which gives the adb shell access using shizuku api. aShell You adds a Modern Design and Material You theme to it with The Support of OTG and Upcoming Wifi Adb :)
=> Added aShell You 

README.md
The old link now requires login
=> Updates the link for Arcticons

README.md
=> Moves some app to 'Privacy & Security'

README.md
Also added a new category called 'Habit Tracker'. I want to add 'Loop Habit Tracker' & 'Sobriety' in this category in another PR.
=> Adds 'Table Habit'

README.md
=> Adds 'SD Maid 2/SE'

README.md
As the creator, I would like more members of the FOSS community to see and enjoy the app, as well as provide them more options and choices. I think the software meets all of your inclusion criteria.
=> Add Chronos as new app entry

README.md
- Calculator You (IzzyOnDroid)
- Dhaaga (Lite) (IzzyOnDroid)
- TermuC
- Conversations Classic
- PSLab
Remove RecordYou and VibeYou as the repos are now archived.
=> August updates

README.md
As noted in #416 Kouchat is inactive; last commit / release years ago.
Are there objections?
/cc @Shakil-Shahadat
=> Remove inactive Kouchat

README.md
[Box, Box!](https://github.com/BrightDV/BoxBox)
=> Adds "Box, Box!"

README.md
https://github.com/Ammar64/Sharing
=> Add Sharing

.github/workflows/ci.yml, ensure_sorted.py
I made a python script to ensure all categories are sorted.  
Currently all it does is to report unsorted categories.  
it currently outputs this
```
Category Battery is not sorted
Category Browser is not sorted
Category Email Clients is not sorted
Category File Sharing is not sorted
Category Image Manipulation is not sorted
Category Maps & Navigation is not sorted
Category RSS Readers is not sorted
Category System is not sorted
Category ToDo Lists is not sorted
Category URL Manipulation is not sorted
Category Utilities is not sorted
Category Wallpapers is not sorted
Category Weather is not sorted
Category Miscellaneous is not sorted
Category Word is not sorted
```
so check those categories  
TODOS
------------
=> Make a python script to check wether all categories are sorted or not

README.md
Fixes the sorting issues, reported by the new CI check.
=> Fix remaining sorting issues

README.md
=> Add encryption category

README.md
reference: https://f-droid.org/en/2024/12/19/twif.html
=> Replace with forks

README.md
https://github.com/Acclorite/book-story
=> Add Book's Story

README.md
- OSS-Dict (https://github.com/farfromrefug/OSS-Dict/issues/6)
- [Ciyue](https://f-droid.org/en/packages/org.eu.mumulhl.ciyue/)
=> Add OSS-Dict and Ciyue

README.md
Seems like app is deprecated or link is broken.
https://github.com/neophtex
Replaced by the other application with the name FlashDim.
=> Replace deprecated app by other project.

README.md
=> AppStore Updated

README.md
=> Educational Game Added

README.md
- Browser apps  
- Compass App
- and many more
=> 7 extra included 

README.md
Added Futo Keyboard And File-Explorer-Compose
Futo Keyboard : https://gitlab.futo.org/keyboard/latinime
File-Explorer-Compose:https://github.com/Raival-e/File-Explorer-Compose
=> Added Keyboard And file Manager

README.md
=> Removes 'Monochromatic'

README.md
PR to add Metrolist - https://github.com/mostafaalagamy/Metrolist
Unsure if this should be added under the Innertune forks but it is substantially different.
=> Add Metrolist

README.md
* Native Alpha
* Quacker
* QuickDic
* µLauncher
* Audio Recorder
* Cuppa
* Stay Put
* Booming Music
* NextCloud Notes
* Meditation
* Breakout 71
=> Added several apps

README.md
[PlugBrain](https://github.com/msbelaid/PlugBrain) is an Android app that helps you reduce screen time and use your phone more mindfully. Instead of simply blocking apps, it adds a twist: after you spend some time on distracting apps, PlugBrain makes you solve a quick math puzzle before continuing.
F-Droid: https://f-droid.org/packages/app.plugbrain.android
=> Add PlugBrain
